api:
  clientId: "client123"
  url: "https://api.url.com"
  key: "api-access-key"
spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver

some.property: "abc"